/** @format */

import { Button } from "@dagbag/dora-helper";
import { getSession, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { Footer } from "../components/Footer";

import Header from "../components/Header";
import Helper from "../components/Helper";
import Navbar from "../components/Navbar";
import Pricing from "../components/Pricing";

export default function Home() {
  const { data: session } = useSession();
  console.log(session);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  return {
    props: { session },
  };
}
